//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSell
    {
        public string orderID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string agentID { get; set; }
        public string paymentMethod { get; set; }
        public string orderItem { get; set; }
        public Nullable<int> orderItemAmount { get; set; }
        public Nullable<decimal> orderPrice { get; set; }
    }
}
